-- ==============================================================================
-- PROJECT REPORT: DATABASE QUERIES, PROCEDURES, AND TRIGGERS MAPPING
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. DDL (Data Definition Language) & Schema Management
-- ------------------------------------------------------------------------------
-- USE CASE: Creates the physical database structures (tables) in the database.
-- LOCATION: Built automatically from 'prisma/schema.prisma' when running `npx prisma db push`.
-- Example DDL generated by the ORM for the AllotmentSessions table:
/*
CREATE TABLE "allotment_sessions" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'DRAFT',
    "portalStatus" TEXT NOT NULL DEFAULT 'CLOSED',
    "blockCutoffsEnabled" BOOLEAN NOT NULL DEFAULT false,
    "maxCgpaDiffEnabled" BOOLEAN NOT NULL DEFAULT false,
    "maxCgpaDiff" DOUBLE PRECISION,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "allotment_sessions_pkey" PRIMARY KEY ("id")
);
*/


-- ------------------------------------------------------------------------------
-- 2. VIEWS (Complex Queries)
-- ------------------------------------------------------------------------------
-- USE CASE: A real-time monitor that joins 4 tables to calculate occupied vs. vacant beds per room.
-- LOCATION: 'scripts/setup-db-extensions.js' (and 'dbms_project_showcase.sql' Part 1A)
CREATE OR REPLACE VIEW vw_room_vacancies AS
SELECT
    b.number            AS block_number,
    b.gender            AS block_gender,
    r."roomNumber",
    r.floor,
    rt.name             AS room_type,
    rt.capacity         AS total_capacity,
    COALESCE(COUNT(a.id), 0)                        AS occupied_beds,
    (rt.capacity - COALESCE(COUNT(a.id), 0))        AS vacant_beds
FROM rooms r
JOIN blocks       b  ON r."blockId"    = b.id
JOIN room_types   rt ON r."roomTypeId" = rt.id
LEFT JOIN allotments a ON a."roomId" = r.id AND a.status = 'ALLOTTED'
GROUP BY b.number, b.gender, r."roomNumber", r.floor, rt.name, rt.capacity;


-- ------------------------------------------------------------------------------
-- 3. TRIGGERS
-- ------------------------------------------------------------------------------
-- USE CASE: Acts as an immutable Audit Log. Anytime a session's status changes, 
-- it automatically writes to an audit table independent of the Node.js application.
-- LOCATION: 'scripts/setup-db-extensions.js' (Lines ~35-65)

-- Step A: The Audit Table
CREATE TABLE IF NOT EXISTS session_audit_log (
    id          SERIAL PRIMARY KEY,
    "sessionId" INTEGER      NOT NULL,
    old_status  VARCHAR(50),
    new_status  VARCHAR(50),
    changed_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

-- Step B: The Trigger Function
CREATE OR REPLACE FUNCTION log_session_status_change()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.status <> OLD.status THEN
        INSERT INTO session_audit_log ("sessionId", old_status, new_status)
        VALUES (OLD.id, OLD.status, NEW.status);
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Step C: Binding the Trigger
CREATE TRIGGER trg_session_status
AFTER UPDATE ON allotment_sessions
FOR EACH ROW EXECUTE FUNCTION log_session_status_change();


-- ------------------------------------------------------------------------------
-- 4. STORED PROCEDURES
-- ------------------------------------------------------------------------------
-- USE CASE: A "Hard Reset" that deletes all allotments and resets the session status 
-- in one highly optimized database execution.
-- LOCATION: 'scripts/setup-db-extensions.js' (Lines ~68-80)
CREATE OR REPLACE PROCEDURE proc_reset_session_allotments(target_session_id INT)
LANGUAGE plpgsql AS $$
DECLARE
    deleted_count INT;
BEGIN
    DELETE FROM allotments WHERE "sessionId" = target_session_id;
    GET DIAGNOSTICS deleted_count = ROW_COUNT;
    UPDATE allotment_sessions SET status = 'DRAFT' WHERE id = target_session_id;
    RAISE NOTICE 'Reset complete. % allotment rows deleted for session %.', deleted_count, target_session_id;
END;
$$;


-- ------------------------------------------------------------------------------
-- 5. CURSORS
-- ------------------------------------------------------------------------------
-- USE CASE: Uses memory-efficient cursors to iterate through waitlisted students 
-- row-by-row, formatting a ranked text report ordered by CGPA.
-- LOCATION: 'dbms_project_showcase.sql' (Part 1D)
CREATE OR REPLACE FUNCTION generate_waitlist_report(target_session_id INT)
RETURNS TEXT LANGUAGE plpgsql AS $$
DECLARE
    waitlist_cursor CURSOR FOR
        SELECT s.name, s."regNo", s.cgpa
        FROM allotments a
        JOIN students s ON a."studentId" = s.id
        WHERE a."sessionId" = target_session_id AND a.status = 'WAITLISTED'
        ORDER BY s.cgpa DESC;
    rec         RECORD;
    report      TEXT := e'--- WAITLIST REPORT ---\n';
    row_rank    INT  := 1;
BEGIN
    OPEN waitlist_cursor;
    LOOP
        FETCH waitlist_cursor INTO rec;
        EXIT WHEN NOT FOUND;
        report := report || row_rank || '. ' || rec.name
                         || ' (' || rec."regNo" || ') — CGPA: '
                         || rec.cgpa || e'\n';
        row_rank := row_rank + 1;
    END LOOP;
    CLOSE waitlist_cursor;
    RETURN report;
END;
$$;


-- ------------------------------------------------------------------------------
-- 6. DML & ATOMIC TRANSACTIONS (BEGIN / ROLLBACK / COMMIT)
-- ------------------------------------------------------------------------------
-- USE CASE: Upserting algorithm cutoff rules via raw SQL. Utilizing ON CONFLICT DO UPDATE.
-- LOCATION: 'dbms_project_showcase.sql' (Part 3D)
BEGIN;
    INSERT INTO block_cutoffs ("sessionId", "blockId", "minCgpa")
    VALUES (
        (SELECT MAX(id) FROM allotment_sessions),
        (SELECT id FROM blocks LIMIT 1),
        8.0
    )
    ON CONFLICT ("sessionId", "blockId") 
    DO UPDATE SET "minCgpa" = EXCLUDED."minCgpa"
    RETURNING "sessionId", "blockId", "minCgpa";
ROLLBACK; -- Used ROLLBACK in showcase to keep data clean, use COMMIT in production.


-- USE CASE: Opening the portal and securely wiping old submissions via Prisma ORM transaction.
-- LOCATION: 'app/api/sessions/[sessionId]/portal/route.js' (Lines ~18-30)
/* Prisma Javascript Equivalent:
await prisma.$transaction(async (tx) => {
    // 1. Update the session status
    await tx.allotmentSession.update({
        where: { id: sessionId },
        data: { portalStatus },
    });

    // 2. Erase existing portal submissions atomically
    if (portalStatus === 'OPEN' && session.portalStatus === 'CLOSED') {
        await tx.portalGroup.deleteMany({
            where: { sessionId },
        });
    }
});
*/


-- ------------------------------------------------------------------------------
-- 7. NORMAL / BASIC QUERIES
-- ------------------------------------------------------------------------------
-- USE CASE: Fetching a single student by Registration Number during login.
-- LOCATION: 'app/api/student/login/route.js' (Lines ~16-19)
/* Prisma Javascript Equivalent:
const student = await prisma.student.findUnique({
    where: { regNo_sessionId: { regNo, sessionId } },
});
*/
-- Raw SQL translation:
-- SELECT * FROM students WHERE "regNo" = '123456' AND "sessionId" = 1 LIMIT 1;


-- USE CASE: Loading the Student Dashboard and fetching grouped relation data.
-- LOCATION: 'app/api/student/dashboard/route.js'
/* Prisma Javascript Equivalent:
const dashboardData = await prisma.student.findUnique({
    where: { id: payload.studentId },
    include: {
        allotments: { include: { room: { include: { block: true, roomType: true } } } }
    }
});
*/
-- Raw SQL translation:
-- SELECT s.*, a.status, r."roomNumber", b.number AS block_number
-- FROM students s
-- LEFT JOIN allotments a ON s.id = a."studentId"
-- LEFT JOIN rooms r      ON a."roomId" = r.id
-- LEFT JOIN blocks b     ON r."blockId" = b.id
-- WHERE s.id = 123;


-- ------------------------------------------------------------------------------
-- 8. AGGREGATIONS & COMPLEX SELECT QUERIES
-- ------------------------------------------------------------------------------
-- USE CASE: Aggregate: Rooms per block (total count and capacity)
-- LOCATION: 'dbms_project_showcase.sql' (Part 2B)
SELECT b.number AS block, b.gender, COUNT(r.id) AS total_rooms, SUM(rt.capacity) AS total_beds
FROM blocks b
JOIN rooms r      ON r."blockId" = b.id
JOIN room_types rt ON r."roomTypeId" = rt.id
GROUP BY b.number, b.gender
ORDER BY b.number;

-- USE CASE: Department-wise CGPA aggregation showing advanced GROUP BY logic.
-- LOCATION: 'dbms_project_showcase.sql' (Part 2E)
SELECT department, COUNT(*) AS student_count, ROUND(AVG(cgpa)::numeric, 2) AS avg_cgpa, MAX(cgpa) AS top_cgpa
FROM students
WHERE "sessionId" = (SELECT MAX(id) FROM allotment_sessions)
GROUP BY department
ORDER BY avg_cgpa DESC;

-- USE CASE: Block occupancy report with Average CGPA per block
-- LOCATION: 'dbms_project_showcase.sql' (Part 2G)
SELECT
    b.number AS block_number, b.gender,
    COUNT(a.id) AS allotted_students,
    ROUND(AVG(s.cgpa)::numeric, 2) AS avg_cgpa
FROM blocks b
JOIN rooms r     ON r."blockId" = b.id
JOIN allotments a ON a."roomId" = r.id
JOIN students s  ON a."studentId" = s.id
WHERE a.status = 'ALLOTTED'
GROUP BY b.number, b.gender
ORDER BY b.number;

-- USE CASE: Load and sort ALL groups by their aggregate average CGPA for the main algorithm engine
-- LOCATION: 'dbms_project_showcase.sql' (Part 5A)
/* Prisma Javascript Equivalent ('lib/allotment-engine.js'):
groups = await prisma.studentGroup.findMany({
    where: { sessionId },
    include: {
        members: { include: { student: true } },
        pref1Block: true, pref1RoomType: true,
        pref2Block: true, pref2RoomType: true,
    },
    orderBy: { avgCgpa: 'desc' },
});
*/
-- Raw SQL translation:
SELECT sg.id, sg."avgCgpa", sg.size, MIN(s.year) AS min_year
FROM student_groups sg
JOIN group_members gm ON sg.id = gm."groupId"
JOIN students s       ON gm."studentId" = s.id
WHERE sg."sessionId" = (SELECT MAX(id) FROM allotment_sessions)
GROUP BY sg.id
ORDER BY sg."avgCgpa" DESC, min_year ASC;


-- ------------------------------------------------------------------------------
-- 9. ADDITIONAL ADVANCED DML QUERIES
-- ------------------------------------------------------------------------------
-- USE CASE: Batch Student CSV Upload demonstrating INSERT ON CONFLICT DO NOTHING natively.
-- LOCATION: 'dbms_project_showcase.sql' (Part 3B) / 'app/api/upload/route.js'
/* Prisma Javascript Equivalent:
await prisma.student.createMany({
    data: studentsBatch,
    skipDuplicates: true,
});
*/
-- Raw SQL translation:
BEGIN;
    INSERT INTO students ("regNo", name, gender, year, department, cgpa, source, "sessionId")
    VALUES
        ('DEMO001', 'Alice Sharma',   'FEMALE', 3, 'CSE',  9.2, 'CSV', (SELECT MAX(id) FROM allotment_sessions)),
        ('DEMO002', 'Bob Patel',      'MALE',   2, 'ECE',  8.7, 'CSV', (SELECT MAX(id) FROM allotment_sessions))
    ON CONFLICT ("regNo", "sessionId") DO NOTHING
    RETURNING "regNo", name, cgpa;
ROLLBACK;


-- USE CASE: Lock Group Preferences with nested relational updates.
-- LOCATION: 'app/api/student/groups/preferences/route.js'
/* Prisma Javascript Equivalent:
await prisma.portalGroup.update({
    where: { id: membership.portalGroupId },
    data: {
        pref1BlockId: p1b, pref1RoomTypeId: p1rt,
        pref2BlockId: p2b, pref2RoomTypeId: p2rt,
        isSubmitted: submit === true,
    },
});
*/
-- Raw SQL translation:
BEGIN;
    UPDATE portal_groups
    SET
        "pref1BlockId"    = (SELECT id FROM blocks ORDER BY id ASC LIMIT 1),
        "pref1RoomTypeId" = (SELECT id FROM room_types ORDER BY id ASC LIMIT 1),
        "pref2BlockId"    = (SELECT id FROM blocks ORDER BY id ASC LIMIT 1 OFFSET 1),
        "pref2RoomTypeId" = (SELECT id FROM room_types ORDER BY id ASC LIMIT 1 OFFSET 1),
        "isSubmitted"     = true
    WHERE id = (SELECT MAX(id) FROM portal_groups)
    RETURNING id, "isSubmitted", "pref1BlockId", "pref2BlockId";
ROLLBACK;


-- USE CASE: Leaving a portal group (Deletes target row securely based on composite conditions).
-- LOCATION: 'app/api/student/groups/leave/route.js'
/* Prisma Javascript Equivalent:
await prisma.portalGroupMember.delete({
    where: { studentId_portalGroupId: { studentId: payload.studentId, portalGroupId: group.id } }
});
*/
-- Raw SQL translation:
BEGIN;
    DELETE FROM portal_group_members
    WHERE "studentId" = (SELECT id FROM students LIMIT 1)
      AND "portalGroupId" = (SELECT MAX(id) FROM portal_groups)
    RETURNING *;
ROLLBACK;


-- ------------------------------------------------------------------------------
-- 10. BATCH ALLOTMENT TRANSACTION (Engine Write-Back)
-- ------------------------------------------------------------------------------
-- USE CASE: Once the Javascript algorithm computes all room assignments in memory, 
-- it writes the final results into the database using a massive atomic batch transaction.
-- This guarantees that if one row fails, the entire allotment rolls back safely.
-- LOCATION: 'lib/allotment-engine.js' (Lines ~360) / 'dbms_project_showcase.sql' (Part 5C)
/* Prisma Javascript Equivalent:
await prisma.$transaction(async (tx) => {
    // Write allotments in chunks...
    await tx.allotment.createMany({ data: currentChunk });
    
    // Update active occupancies on existing rooms...
    await tx.room.update({
        where: { id: roomId },
        data: { occupiedBeds: newOccupancy }
    });
    
    // Finally, update session status...
    await tx.allotmentSession.update({
        where: { id: sessionId },
        data: { status: 'ROUND1_DONE' },
    });
});
*/
-- Raw SQL translation (Simplified to a single statement representation):
BEGIN;
    INSERT INTO allotments ("studentId", "roomId", "groupId", "round", status, "sessionId")
    SELECT
        s.id,
        r.id,
        1,                      -- Engine computes this
        1,
        'ALLOTTED',
        s."sessionId"
    FROM students s
    CROSS JOIN rooms r
    WHERE s."sessionId" = (SELECT MAX(id) FROM allotment_sessions)
    LIMIT 1;                    -- Simplified for demo
    
    -- Additional queries updating Room Occupancy and Session Status here
COMMIT;
