import { NextResponse } from 'next/server';
import prisma from '@/lib/prisma';

// GET /api/admin/audit-logs
// Fetches the raw session audit logs generated by the Postgres DB trigger
export async function GET(request) {
    try {
        // Fetch raw logs joined with session names for human readability
        const logs = await prisma.$queryRaw`
            SELECT 
                l.id,
                l."sessionId",
                l.old_status,
                l.new_status,
                l.changed_at,
                s.name as session_name
            FROM session_audit_log l
            LEFT JOIN allotment_sessions s ON l."sessionId" = s.id
            ORDER BY l.changed_at DESC
            LIMIT 100
        `;

        return NextResponse.json({ logs });
    } catch (error) {
        console.error('Failed to fetch audit logs:', error);
        return NextResponse.json({ error: 'Failed to fetch audit logs' }, { status: 500 });
    }
}
