import { NextResponse } from 'next/server';
import prisma from '@/lib/prisma';

// GET /api/admin/audit-logs
// Fetches the raw session audit logs generated by the Postgres DB trigger.
// Returns an empty array (not an error) if the table doesn't exist yet —
// the admin must click "Setup DB Trigger" first.
export async function GET() {
    try {
        const logs = await prisma.$queryRaw`
            SELECT 
                l.id,
                l."sessionId",
                l.old_status,
                l.new_status,
                l.changed_at,
                s.name as session_name
            FROM session_audit_log l
            LEFT JOIN allotment_sessions s ON l."sessionId" = s.id
            ORDER BY l.changed_at DESC
            LIMIT 100
        `;
        return NextResponse.json({ logs });
    } catch (error) {
        // Table doesn't exist yet — return empty gracefully so admin UI doesn't crash
        if (error.message?.includes('session_audit_log') || error.code === '42P01') {
            return NextResponse.json({
                logs: [],
                warning: 'Audit log table not set up. Click "Setup DB Trigger" to initialize.',
            });
        }
        console.error('Failed to fetch audit logs:', error);
        return NextResponse.json({ error: 'Failed to fetch audit logs' }, { status: 500 });
    }
}
